# Generated by Django 5.0.4 on 2024-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_social_media', '0003_post_is_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_comment',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
